/**
 * CLI command: overstory hooks install|uninstall|status
 *
 * Manages orchestrator hooks in platform-specific settings files.
 * Hooks are sourced from .overstory/hooks.json (generated by overstory init).
 *
 * This keeps the canonical hook configuration in .overstory/ while placing
 * a minimal copy in the platform's settings only when the user explicitly opts in.
 * Running `overstory init` alone does NOT modify platform settings — the user must
 * run `overstory hooks install` as a separate step.
 *
 * Supports Opencode (.opencode/settings.json) platform.
 */

import { mkdir, unlink } from "node:fs/promises";
import { join } from "node:path";
import { loadConfig } from "../config.ts";
import { ValidationError } from "../errors.ts";
import { createPlatform } from "../platform/factory.ts";

const HOOKS_HELP = `overstory hooks — Manage orchestrator hooks

Usage: overstory hooks <subcommand>

Subcommands:
  install                  Install orchestrator hooks to platform settings
  uninstall                Remove orchestrator hooks from platform settings
  status                   Check if hooks are installed

Options:
  --force                  Overwrite existing hooks
  --json                   Output as JSON
  --help, -h               Show this help

Hooks source: .overstory/hooks.json (generated by overstory init)
Hooks target: .opencode/settings.json`;

/**
 * Get the settings file name for the current platform.
 */
function getSettingsFileName(platformId: string): string {
	// Claude Code uses settings.local.json, Opencode uses settings.json
	return platformId === "opencode" ? "settings.json" : "settings.local.json";
}

/**
 * Install orchestrator hooks from .overstory/hooks.json to platform settings.
 *
 * Reads the canonical hook config from .overstory/hooks.json and writes it to
 * the platform's settings file. Preserves any existing non-hooks keys.
 */
async function installHooks(args: string[]): Promise<void> {
	const force = args.includes("--force");
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;
	const platform = await createPlatform(config.platform.type);

	// Read source hooks from .overstory/hooks.json
	const sourcePath = join(projectRoot, ".overstory", "hooks.json");
	const sourceFile = Bun.file(sourcePath);
	if (!(await sourceFile.exists())) {
		throw new ValidationError("No hooks.json found in .overstory/. Run 'overstory init' first.", {
			field: "source",
		});
	}

	const sourceContent = await sourceFile.text();
	const sourceHooks = JSON.parse(sourceContent) as Record<string, unknown>;

	// Get platform-specific target directory and file name
	const targetDir = platform.getContextDir(projectRoot);
	const settingsFileName = getSettingsFileName(platform.id);
	const targetPath = join(targetDir, settingsFileName);
	const targetFile = Bun.file(targetPath);

	let targetConfig: Record<string, unknown> = {};
	if (await targetFile.exists()) {
		const existingContent = await targetFile.text();
		const existing = JSON.parse(existingContent) as Record<string, unknown>;

		if (existing.hooks && !force) {
			process.stdout.write(`Hooks already present in ${targetPath}\nUse --force to overwrite.\n`);
			return;
		}

		// Preserve non-hooks keys (e.g., env settings)
		targetConfig = existing;
	}

	// Merge: set hooks from source, preserve other keys
	targetConfig.hooks = sourceHooks.hooks;

	// Write
	await mkdir(targetDir, { recursive: true });
	await Bun.write(targetPath, `${JSON.stringify(targetConfig, null, "\t")}\n`);

	process.stdout.write(`\u2713 Installed orchestrator hooks to ${targetPath}\n`);
	process.stdout.write("  Source: .overstory/hooks.json\n");
}

/**
 * Remove orchestrator hooks from platform settings.
 *
 * If hooks were the only content, removes the file entirely.
 * Otherwise, preserves other keys and only removes the hooks key.
 */
async function uninstallHooks(_args: string[]): Promise<void> {
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;
	const platform = await createPlatform(config.platform.type);

	const targetDir = platform.getContextDir(projectRoot);
	const settingsFileName = getSettingsFileName(platform.id);
	const targetPath = join(targetDir, settingsFileName);
	const targetFile = Bun.file(targetPath);

	if (!(await targetFile.exists())) {
		process.stdout.write(`No ${targetPath} found — nothing to uninstall.\n`);
		return;
	}

	const content = await targetFile.text();
	const parsed = JSON.parse(content) as Record<string, unknown>;

	if (!parsed.hooks) {
		process.stdout.write(`No hooks found in ${targetPath} — nothing to uninstall.\n`);
		return;
	}

	// Separate hooks from other settings
	const { hooks: _hooks, ...rest } = parsed;

	const remainingKeys = Object.keys(rest);
	if (remainingKeys.length === 0) {
		await unlink(targetPath);
		process.stdout.write(`\u2713 Removed ${targetPath} (was hooks-only)\n`);
	} else {
		await Bun.write(targetPath, `${JSON.stringify(rest, null, "\t")}\n`);
		process.stdout.write(`\u2713 Removed hooks from ${targetPath} (preserved other settings)\n`);
	}
}

/**
 * Show hooks installation status.
 */
async function statusHooks(args: string[]): Promise<void> {
	const json = args.includes("--json");
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;
	const platform = await createPlatform(config.platform.type);

	const sourcePath = join(projectRoot, ".overstory", "hooks.json");
	const targetDir = platform.getContextDir(projectRoot);
	const settingsFileName = getSettingsFileName(platform.id);
	const targetPath = join(targetDir, settingsFileName);

	const sourceExists = await Bun.file(sourcePath).exists();
	const targetExists = await Bun.file(targetPath).exists();

	let installed = false;
	if (targetExists) {
		const content = await Bun.file(targetPath).text();
		const parsed = JSON.parse(content) as Record<string, unknown>;
		installed = !!parsed.hooks;
	}

	if (json) {
		process.stdout.write(`${JSON.stringify({ sourceExists, installed })}\n`);
	} else {
		process.stdout.write(
			`Hooks source (.overstory/hooks.json): ${sourceExists ? "present" : "missing"}\n`,
		);
		process.stdout.write(`Hooks installed (${targetPath}): ${installed ? "yes" : "no"}\n`);
		if (!installed && sourceExists) {
			process.stdout.write(`\nRun 'overstory hooks install' to install.\n`);
		}
	}
}

/**
 * Entry point for `overstory hooks <subcommand>`.
 */
export async function hooksCommand(args: string[]): Promise<void> {
	if (args.includes("--help") || args.includes("-h") || args.length === 0) {
		process.stdout.write(`${HOOKS_HELP}\n`);
		return;
	}

	const subcommand = args[0];
	const subArgs = args.slice(1);

	switch (subcommand) {
		case "install":
			await installHooks(subArgs);
			break;
		case "uninstall":
			await uninstallHooks(subArgs);
			break;
		case "status":
			await statusHooks(subArgs);
			break;
		default:
			throw new ValidationError(
				`Unknown hooks subcommand: ${subcommand}. Run 'overstory hooks --help' for usage.`,
				{ field: "subcommand", value: subcommand },
			);
	}
}
