#!/usr/bin/env bun
/**
 * Build script that embeds agent definition files as TypeScript strings.
 * Run this before building the binary to generate src/agents/embedded.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const agentFiles = [
	"builder.md",
	"coordinator.md",
	"lead.md",
	"merger.md",
	"monitor.md",
	"reviewer.md",
	"scout.md",
	"supervisor.md",
];

const agentsDir = join(import.meta.dir, "..", "agents");
const outputPath = join(import.meta.dir, "..", "src", "agents", "embedded.ts");

let output = `// Auto-generated by scripts/embed-agents.ts
// Do not edit manually - run 'bun scripts/embed-agents.ts' to regenerate

export const EMBEDDED_AGENTS: Record<string, string> = {\n`;

for (const fileName of agentFiles) {
	const filePath = join(agentsDir, fileName);
	const content = readFileSync(filePath, "utf-8");
	// Escape backticks and ${} for template literal
	const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
	output += `\t"${fileName}": \`${escaped}\`,\n`;
}

output += `};\n`;

writeFileSync(outputPath, output);
console.log(`Generated ${outputPath} with ${agentFiles.length} agent definitions`);
