#!/usr/bin/env bun
/**
 * Build script that embeds template files as TypeScript strings.
 * Run this before building the binary to generate src/templates-embedded.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const templateFiles = [
	{ name: "HOOKS", path: "templates/hooks.json.tmpl" },
	{ name: "OVERLAY", path: "templates/overlay.md.tmpl" },
	{ name: "OPENCODE_HOOKS", path: "templates/opencode-hooks.json.tmpl" },
];

const rootDir = join(import.meta.dir, "..");
const outputPath = join(import.meta.dir, "..", "src", "templates-embedded.ts");

let output = `// Auto-generated by scripts/embed-templates.ts
// Do not edit manually - run 'bun scripts/embed-templates.ts' to regenerate

export const EMBEDDED_TEMPLATES = {\n`;

for (const { name, path } of templateFiles) {
	const filePath = join(rootDir, path);
	const content = readFileSync(filePath, "utf-8");
	// Escape backticks and ${} for template literal
	const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
	output += `\t${name}: \`${escaped}\`,\n`;
}

output += `} as const;\n`;
output += `\nexport type TemplateName = keyof typeof EMBEDDED_TEMPLATES;\n`;

writeFileSync(outputPath, output);
console.log(`Generated ${outputPath} with ${templateFiles.length} templates`);
