// Auto-generated by scripts/embed-templates.ts
// Do not edit manually - run 'bun scripts/embed-templates.ts' to regenerate

export const EMBEDDED_TEMPLATES = {
	HOOKS: `{
	"hooks": {
		"SessionStart": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory prime --agent {{AGENT_NAME}}"
					}
				]
			}
		],
		"UserPromptSubmit": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory mail check --inject --agent {{AGENT_NAME}}"
					}
				]
			}
		],
		"PreToolUse": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory log tool-start --agent {{AGENT_NAME}} --stdin"
					}
				]
			},
			{
				"matcher": "Bash",
				"hooks": [
					{
						"type": "command",
						"command": "read -r INPUT; CMD=\$(echo \\"\$INPUT\\" | sed 's/.*\\"command\\": *\\"\\\\([^\\"]*\\\\)\\".*/\\\\1/'); if echo \\"\$CMD\\" | grep -qE '\\\\bgit\\\\s+push\\\\b'; then echo '{\\"decision\\":\\"block\\",\\"reason\\":\\"git push is blocked — use overstory merge to integrate changes, push manually when ready\\"}'; exit 0; fi;"
					}
				]
			}
		],
		"PostToolUse": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory log tool-end --agent {{AGENT_NAME}} --stdin"
					},
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory mail check --inject --agent {{AGENT_NAME}} --debounce 500"
					}
				]
			},
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory mail check --inject --agent {{AGENT_NAME}} --debounce 30000"
					}
				]
			},
			{
				"matcher": "Bash",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; read -r INPUT; if echo \\"\$INPUT\\" | grep -qE '\\\\bgit\\\\s+commit\\\\b'; then mulch diff HEAD~1 >/dev/null 2>&1 || true; fi; exit 0;"
					}
				]
			}
		],
		"Stop": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory log session-end --agent {{AGENT_NAME}} --stdin"
					},
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; mulch learn"
					}
				]
			}
		],
		"PreCompact": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory prime --agent {{AGENT_NAME}} --compact"
					}
				]
			}
		]
	}
}
`,
	OVERLAY: `# DO NOT EDIT — Auto-generated by overstory
# This overlay was written by \`overstory sling\`. Manual edits will be
# overwritten on the next spawn. Modify the template at
# templates/overlay.md.tmpl in the overstory repo instead.

{{#if claude}}
# Claude Code Context
This agent is running on the Claude Code platform.
Context location: \`.claude/CLAUDE.md\`
{{/if}}
{{#if opencode}}
# Opencode Context
This agent is running on the Opencode platform.
Context location: \`AGENTS.md\`
{{/if}}

{{BASE_DEFINITION}}

---

## Your Assignment

- **Agent Name:** {{AGENT_NAME}}
- **Task ID:** {{BEAD_ID}}
- **Spec:** {{SPEC_PATH}}
- **Branch:** {{BRANCH_NAME}}
- **Worktree:** {{WORKTREE_PATH}}
- **Parent:** {{PARENT_AGENT}}
- **Depth:** {{DEPTH}}

{{SPEC_INSTRUCTION}}

{{SKIP_SCOUT}}

## Working Directory

Your worktree root is: \`{{WORKTREE_PATH}}\`

**CRITICAL**: All file operations MUST use paths within this directory.
- Use paths relative to your worktree root, or absolute paths starting with \`{{WORKTREE_PATH}}\`
- Writing to the canonical repo root instead of your worktree is a critical error (PATH_BOUNDARY_VIOLATION)
- You may READ files from the canonical repo for context, but all WRITES go to your worktree

## File Scope (exclusive ownership)

These paths are relative to your worktree root: \`{{WORKTREE_PATH}}\`

You may ONLY modify the files listed below within your worktree. Do not touch any other files.
If you need changes outside your scope, send mail to your parent agent
requesting the modification.

{{FILE_SCOPE}}

## Expertise

Prime relevant domain knowledge before starting work:

{{MULCH_DOMAINS}}

{{MULCH_EXPERTISE}}

## Communication

Use \`overstory mail\` for all communication. Your address is **{{AGENT_NAME}}**.

\`\`\`bash
# Check your inbox (do this regularly)
overstory mail check --agent {{AGENT_NAME}}

# Send a status update to your parent
overstory mail send --to {{PARENT_AGENT}} --subject "status" \\
  --body "Progress update here" --type status --agent {{AGENT_NAME}}

# Ask a question
overstory mail send --to {{PARENT_AGENT}} --subject "question" \\
  --body "Your question here" --type question --priority high --agent {{AGENT_NAME}}

# Report completion
overstory mail send --to {{PARENT_AGENT}} --subject "done" \\
  --body "Summary of what was done" --type result --agent {{AGENT_NAME}}

# Reply to a message
overstory mail reply <message-id> --body "Your reply" --agent {{AGENT_NAME}}
\`\`\`

## Spawning Sub-Workers

{{CAN_SPAWN}}

{{QUALITY_GATES}}

{{CONSTRAINTS}}
`,
	OPENCODE_HOOKS: `{
	"hooks": {
		"SessionStart": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory prime --agent {{AGENT_NAME}}"
					}
				]
			}
		],
		"UserPromptSubmit": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory mail check --inject --agent {{AGENT_NAME}}"
					}
				]
			}
		],
		"PreToolUse": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory log tool-start --agent {{AGENT_NAME}} --stdin"
					}
				]
			},
			{
				"matcher": "Bash",
				"hooks": [
					{
						"type": "command",
						"command": "read -r INPUT; CMD=\$(echo \\"\$INPUT\\" | sed 's/.*\\"command\\": *\\"\\\\([^\\"]*\\\\)\\".*/\\\\1/'); if echo \\"\$CMD\\" | grep -qE '\\\\bgit\\\\s+push\\\\b'; then echo '{\\"decision\\":\\"block\\",\\"reason\\":\\"git push is blocked — use overstory merge to integrate changes, push manually when ready\\"}'; exit 0; fi;"
					}
				]
			}
		],
		"PostToolUse": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory log tool-end --agent {{AGENT_NAME}} --stdin"
					},
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory mail check --inject --agent {{AGENT_NAME}} --debounce 500"
					}
				]
			},
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory mail check --inject --agent {{AGENT_NAME}} --debounce 30000"
					}
				]
			},
			{
				"matcher": "Bash",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; read -r INPUT; if echo \\"\$INPUT\\" | grep -qE '\\\\bgit\\\\s+commit\\\\b'; then mulch diff HEAD~1 >/dev/null 2>&1 || true; fi; exit 0;"
					}
				]
			}
		],
		"Stop": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory log session-end --agent {{AGENT_NAME}} --stdin"
					},
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; mulch learn"
					}
				]
			}
		],
		"PreCompact": [
			{
				"matcher": "",
				"hooks": [
					{
						"type": "command",
						"command": "[ -z \\"\$OVERSTORY_AGENT_NAME\\" ] && exit 0; overstory prime --agent {{AGENT_NAME}} --compact"
					}
				]
			}
		]
	}
}
`,
} as const;

export type TemplateName = keyof typeof EMBEDDED_TEMPLATES;
